[platformio]
default_envs = c5_bringup

[env:c5_bringup]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = espidf
board = blacksheep_esp32c5_wroom_1u_n32r8
upload_protocol = esptool
monitor_speed = 115200
monitor_filters = direct
monitor_dtr = 0
monitor_rts = 0
extra_scripts = post:scripts/native_bootloader.py

[env:c5_5ghz_validation]
extends = env:c5_bringup
build_flags = -DWIFI_VALIDATION_5GHZ=1

[env:c5_passive_validation]
extends = env:c5_bringup
build_flags = -DWIFI_PASSIVE_VALIDATION=1

[env:c5_passive_5ghz_validation]
extends = env:c5_bringup
build_flags =
    -DWIFI_PASSIVE_VALIDATION=1
    -DWIFI_VALIDATION_5GHZ=1

[env:c5_channel_control_24ghz]
extends = env:c5_bringup
build_flags = -DWIFI_CHANNEL_CONTROL_VALIDATION=1

[env:c5_channel_control_5ghz]
extends = env:c5_bringup
build_flags =
    -DWIFI_CHANNEL_CONTROL_VALIDATION=1
    -DWIFI_VALIDATION_5GHZ=1

[env:c5_metadata_24ghz]
extends = env:c5_bringup
build_flags = -DWIFI_METADATA_CHARACTERIZATION=1

[env:c5_metadata_5ghz]
extends = env:c5_bringup
build_flags =
    -DWIFI_METADATA_CHARACTERIZATION=1
    -DWIFI_VALIDATION_5GHZ=1
